columnSuffix: null
contentColumnType: string
fieldGroup: 7fedfd05-fc2b-4e07-b9a9-6491b9053486 # Simgle Fields
handle: aboutImage
instructions: ''
name: 'About Image'
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:726db28d-741a-413e-8de5-6e51d8b5b409' # Blog
  defaultUploadLocationSubpath: ''
  limit: ''
  localizeRelations: false
  previewMode: full
  restrictFiles: '1'
  selectionLabel: ''
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:6467e123-7db4-48ef-a3de-a07b582add4d' # General
  singleUploadLocationSubpath: ''
  source: null
  sources: '*'
  targetSiteId: null
  useSingleFolder: true
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
