columnSuffix: null
contentColumnType: string
fieldGroup: bf0c087a-c268-487f-9349-fa33e37c9b0a # Blog Post Fields
handle: postContent
instructions: ''
name: 'Post Content'
searchable: false
settings:
  contentTable: '{{%matrixcontent_postcontent}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
