fieldLayouts:
  5f225f0e-56b5-4e80-805a-9a6655932fa6:
    tabs:
      -
        elements:
          -
            fieldUid: 245f7b1d-5986-46bd-954a-feb474375124 # Site Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Information
        sortOrder: 1
handle: siteInformation
name: 'Site Information'
sortOrder: 1
