defaultPlacement: end
enableVersioning: true
handle: about
name: About
propagationMethod: all
siteSettings:
  4a59f10b-4e8b-47a6-81b2-86311741e598: # FirstCraft
    enabledByDefault: true
    hasUrls: true
    template: _singles/about
    uriFormat: about
type: single
